{
 "title": "MagicOnion Overview",
 "description": "overview of MagicOnion metrics collected via Open Telemetry",
 "tags": [
  "magiconion",
  "opentelemetry",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Unary Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(magiconion_unary_requests_count{app=\"magiconion\"})",
     "legendFormat": "Unary Requests"
    }
   ]
  },
  {
   "title": "Streaming Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(magiconion_streaminghub_requests_count{app=\"magiconion\"})",
     "legendFormat": "Streaming Requests"
    }
   ]
  },
  {
   "title": "Current Unary Elapsed(Max)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(magiconion_unary_elapsed_milliseconds_sum{app=\"magiconion\"})"
    }
   ]
  },
  {
   "title": "Current StreamingHub Elapsed(Max)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(magiconion_streaminghub_elapsed_milliseconds_sum{app=\"magiconion\"})"
    }
   ]
  },
  {
   "title": "Unary RequestSize",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(magiconion_unary_request_size_sum{app=\"magiconion\"})",
     "legendFormat": "UnaryRequestSize"
    }
   ]
  },
  {
   "title": "Unary ResponseSize",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(magiconion_unary_response_size_sum{app=\"magiconion\"})",
     "legendFormat": "UnaryResponseSize"
    }
   ]
  },
  {
   "title": "Streaming Hub RequestSize",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(magiconion_streaminghub_request_size_sum{app=\"magiconion\"})",
     "legendFormat": "StreamingHubRequestSize"
    }
   ]
  },
  {
   "title": "Streaming Hub ResponseSize",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(magiconion_streaminghub_response_size_sum{app=\"magiconion\"})",
     "legendFormat": "StreamingHubResponseSize"
    }
   ]
  },
  {
   "title": "Unary Request Detail",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "magiconion_unary_requests_count{app=\"magiconion\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Unary Elapsed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "magiconion_unary_elapsed_milliseconds_sum{app=\"magiconion\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Unary RequestSize",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "magiconion_unary_request_size_sum{app=\"magiconion\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Streaming Hub RequestSize",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "magiconion_streaminghub_request_size_sum{app=\"magiconion\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Streaming Request Details",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "magiconion_streaminghub_requests_count{app=\"magiconion\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "StreamingHub Elapsed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "magiconion_streaminghub_elapsed_milliseconds_sum{app=\"magiconion\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Unary ResponseSize",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "magiconion_unary_response_size_sum{app=\"magiconion\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Streaming Hub ResponseSize",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "magiconion_streaminghub_response_size_sum{app=\"magiconion\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Current Duplex Connects",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(magiconion_streaminghub_connect_count{app=\"magiconion\"}) - sum(magiconion_streaminghub_disconnect_count{app=\"magiconion\"})",
     "legendFormat": "Duplex Connect"
    }
   ]
  },
  {
   "title": "UnaryErrorCount(Total)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(magiconion_unary_error_count{app=\"magiconion\"})",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "StreamingHubErrorCount(Total)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(magiconion_streaminghub_error_count{app=\"magiconion\"})",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Build Service Definitions(Total)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "magiconion_buildservicedefinition_duration_milliseconds_count{app=\"magiconion\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Connects/Disconnects",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "magiconion_streaminghub_connect_count{app=\"magiconion\"}",
     "legendFormat": "Connect"
    },
    {
     "expr": "magiconion_measure_disconnect{app=\"magiconion\"}",
     "legendFormat": "Disconnect"
    }
   ]
  },
  {
   "title": "UnaryErrorCount",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "magiconion_unary_error_count{app=\"magiconion\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "StreamingHubErrorCount",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "magiconion_streaminghub_error_count{app=\"magiconion\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Build Service Definitions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "magiconion_buildservicedefinition_duration_milliseconds_count{app=\"magiconion\"}",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}