{
 "title": "MagicOnion Overview",
 "description": "overview of MagicOnion metrics collected via Open Telemetry",
 "tags": [
  "magiconion",
  "opentelemetry",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Current Duplex Connects",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(magiconion_streaminghub_connect_count{app=\"magiconion\"}) - sum(magiconion_streaminghub_disconnect_count{app=\"magiconion\"})",
     "legendFormat": "Duplex Connect"
    }
   ]
  },
  {
   "title": "Connects/Disconnects",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "magiconion_streaminghub_connect_count{app=\"magiconion\"}",
     "legendFormat": "Connect"
    },
    {
     "expr": "magiconion_measure_disconnect{app=\"magiconion\"}",
     "legendFormat": "Disconnect"
    }
   ]
  },
  {
   "title": "Current Unary Elapsed(Max)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(magiconion_unary_elapsed_milliseconds_sum{app=\"magiconion\"})"
    }
   ]
  },
  {
   "title": "Current StreamingHub Elapsed(Max)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(magiconion_streaminghub_elapsed_milliseconds_sum{app=\"magiconion\"})"
    }
   ]
  },
  {
   "title": "UnaryErrorCount(Current)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(magiconion_unary_error_count{app=\"magiconion\"})",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "StreamingHubErrorCount(Current)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(magiconion_streaminghub_error_count{app=\"magiconion\"})",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Unary ResponseSize",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(magiconion_unary_response_size_sum{app=\"magiconion\"})",
     "legendFormat": "UnaryResponseSize"
    }
   ]
  },
  {
   "title": "Streaming Hub ResponseSize",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(magiconion_streaminghub_response_size_sum{app=\"magiconion\"})",
     "legendFormat": "StreamingHubResponseSize"
    }
   ]
  },
  {
   "title": "Unary Requests",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(magiconion_unary_requests_count{app=\"magiconion\"})",
     "legendFormat": "Unary Requests"
    }
   ]
  },
  {
   "title": "Unary Request Detail",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "magiconion_unary_requests_count{app=\"magiconion\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Unary Elapsed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "magiconion_unary_elapsed_milliseconds_sum{app=\"magiconion\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "UnaryErrorCount",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "magiconion_unary_error_count{app=\"magiconion\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Unary ResponseSize",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "magiconion_unary_response_size_sum{app=\"magiconion\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Streaming Requests",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(magiconion_streaminghub_requests_count{app=\"magiconion\"})",
     "legendFormat": "Streaming Requests"
    }
   ]
  },
  {
   "title": "Streaming Request Details",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "magiconion_streaminghub_requests_count{app=\"magiconion\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "StreamingHub Elapsed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "magiconion_streaminghub_elapsed_milliseconds_sum{app=\"magiconion\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "StreamingHubErrorCount",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "magiconion_streaminghub_error_count{app=\"magiconion\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Streaming Hub ResponseSize",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "magiconion_streaminghub_response_size_sum{app=\"magiconion\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Build Service Definitions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "magiconion_buildservicedefinition_duration_milliseconds_count{app=\"magiconion\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum by (container_name)(rate(container_cpu_usage_seconds_total{image!=\"\",container_label_com_docker_compose_service=\"magiconion\"}[1m]))) / count(node_cpu_seconds_total{mode=\"system\"}) * 100"
    }
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "container_cpu_load_average_10s{image!=\"\",container_label_com_docker_compose_service=\"magiconion\"}",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Container Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_max_usage_bytes{image!=\"\",container_label_com_docker_compose_service=\"magiconion\"}",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  }
 ]
}