{
 "title": "MagicOnion Overview",
 "description": "overview of MagicOnion metrics collected via Open Telemetry",
 "tags": [
  "magiconion",
  "opentelemetry",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Connects/Disconnects",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "MagicOnion_measure_Connect{instance=\"magiconion:9182\",job=\"magiconion\"}",
     "legendFormat": "Connect"
    },
    {
     "expr": "MagicOnion_measure_Disconnect{instance=\"magiconion:9182\",job=\"magiconion\"}",
     "legendFormat": "Disconnect"
    }
   ]
  },
  {
   "title": "Current Unary Elapsed(Max)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(MagicOnion_measure_UnaryElapsed{job=\"magiconion\"})"
    }
   ]
  },
  {
   "title": "Current StreamingHub Elapsed(Max)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(MagicOnion_measure_StreamingHubElapsed{job=\"magiconion\"})"
    }
   ]
  },
  {
   "title": "Current Unary ErrorCount",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "MagicOnion_measure_UnaryErrorCount{job=\"magiconion\"}",
     "legendFormat": "{{MagicOnion_keys_Method}}"
    }
   ]
  },
  {
   "title": "Current StreamingHub ErrorCount",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "MagicOnion_measure_StreamingHubErrorCount{instance=\"magiconion:9182\",job=\"magiconion\"}",
     "legendFormat": "{{MagicOnion_keys_Method}}"
    }
   ]
  },
  {
   "title": "Unary ResponseSize",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(MagicOnion_measure_UnaryResponseSize)",
     "legendFormat": "StreamingHubResponseSize"
    }
   ]
  },
  {
   "title": "StreamingHub ResponseSize",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(MagicOnion_measure_StreamingHubResponseSize)",
     "legendFormat": "StreamingHubResponseSize"
    }
   ]
  },
  {
   "title": "Connects/Disconnects",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "MagicOnion_measure_Connect{instance=\"magiconion:9182\",job=\"magiconion\"}",
     "legendFormat": "Connect"
    },
    {
     "expr": "MagicOnion_measure_Disconnect{instance=\"magiconion:9182\",job=\"magiconion\"}",
     "legendFormat": "Disconnect"
    }
   ]
  },
  {
   "title": "Unary Elapsed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "MagicOnion_measure_UnaryElapsed{instance=\"magiconion:9182\",job=\"magiconion\"}",
     "legendFormat": "{{MagicOnion_keys_Method}}"
    }
   ]
  },
  {
   "title": "Unary ErrorCount",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "MagicOnion_measure_UnaryErrorCount{instance=\"magiconion:9182\",job=\"magiconion\"}",
     "legendFormat": "{{MagicOnion_keys_Method}}"
    }
   ]
  },
  {
   "title": "Unary ResponseSize",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "MagicOnion_measure_UnaryResponseSize{instance=\"magiconion:9182\",job=\"magiconion\"}",
     "legendFormat": "{{MagicOnion_keys_Method}}"
    }
   ]
  },
  {
   "title": "Build Service Definitions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "MagicOnion_measure_BuildServiceDefinition{instance=\"magiconion:9182\",job=\"magiconion\"}",
     "legendFormat": "{{MagicOnion_keys_Method}}"
    }
   ]
  },
  {
   "title": "StreamingHub Elapsed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "MagicOnion_measure_StreamingHubElapsed{instance=\"magiconion:9182\",job=\"magiconion\"}",
     "legendFormat": "{{MagicOnion_keys_Method}}"
    }
   ]
  },
  {
   "title": "StreamingHub ErrorCount",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "MagicOnion_measure_StreamingHubErrorCount{instance=\"magiconion:9182\",job=\"magiconion\"}",
     "legendFormat": "{{MagicOnion_keys_Method}}"
    }
   ]
  },
  {
   "title": "StreamingHub ResponseSize",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "MagicOnion_measure_StreamingHubResponseSize{instance=\"magiconion:9182\",job=\"magiconion\"}",
     "legendFormat": "{{MagicOnion_keys_Method}}"
    }
   ]
  }
 ]
}